#!/bin/bash

EXIT_STATUS=0

printf "TEST LOG:\n\n" > ./log.txt
rm -f .coverage

pycodestyle ./*.py
EXIT_STATUS=$?

if [ $EXIT_STATUS -ne 0 ]; then
    if [[ -n ${USE_BANNER} ]]; then
        figlet -f banner PEP-8 FAILED
    else
        printf "\nPEP-8 FAILED\n\n"
    fi
    exit $EXIT_STATUS
fi

pylint -rn --disable=C0325,W1201 --msg-template='{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}' ./*.py
EXIT_STATUS=$?

if [ $EXIT_STATUS -ne 0 ]; then
    if [[ -n ${USE_BANNER} ]]; then
        figlet -f banner PYLINT FAILED
    else
        printf "\nPYLINT FAILED\n\n"
    fi
    exit $EXIT_STATUS
fi

for t in ./tc_*.py
do
    declare cov=${t#./tc_}; cov=".coverage_${cov%.py}"
    printf "TEST: $t\n"
    COVERAGE_FILE=${cov} coverage run $t >> ./log.txt || EXIT_STATUS=$?
done

if [ $EXIT_STATUS -eq 0 ]; then
    # SUCCESS
    if [[ -n ${USE_BANNER} ]]; then
        figlet -f banner TESTS PASSED
    else
        printf "\nTESTS PASSED\n\n"
    fi
    # Report coverage
    coverage combine .coverage_*
    coverage report -m --omit='*site-packages*,*dist-packages*'

    # Alert user, if say enabled.
    # todo: set up for espeak on Linux
    if [[ -n ${USE_SAY} ]]; then
        lastline=$(coverage report -m --omit='*site-packages*,*dist-packages*' | tail -1)
        lastlinewords=($lastline)
        coverage=${lastlinewords[3]}
        (say "Hell yes, the tests all passed and total test coverage is ${coverage}" &);
    fi
else
    # FAILURE
    if [[ -n ${USE_BANNER} ]]; then
        figlet -f banner TESTS FAILED
    else
        printf "\nTESTS FAILED\n\n"
    fi
    if [[ -n ${USE_SAY} ]]; then
        (say "Dammit, the code's broke" &);
    fi
fi
