#!/usr/bin/env python3

"""
Top level program.  Execution/invocation starts here.
"""

import sys
import main

if __name__ == '__main__':  # pragma: no cover
    status = main.main(sys.argv[1:])
    sys.exit(status)
